### PR TITLE
Revert to 0 and update YAML files

### PR DESCRIPTION
**Pull request by sinsukehlab**
- Revert some commits by @github-actions to reset STEP to 0
- (Update update-step.sh to enable it to close Step 0 in README.md)
- Fix the conditional expressions in the YAML files
- Edit the YAML files so that they could use skills/action-update-step@v1 to update steps
- Fix the YAML files so that the workflows could function without any error or skip
- Change the style of conditional expressions in the YAML files
- Clearly indicate the wait in README.md
- Enable echoing workflow commands

### Why:

The latest commits by @github-actions have updated STEP, README.md, and _sidebar.md.
STEP should be set to 0 when generated, and then be updated to 1 by @github-actions closing Step 0 in README.md.
Also, a check in Step 3 is skipped even if the learner follows the instructions.

### What's being changed:

- I reverted recent commits by @github-actions to reset STEP to 0.
- I then updated update-step.sh to enable it to close Step 0 in README.md. (now deprecated)
- I fixed the conditional expressions in the YAML files.
- I edited the YAML files so that they could use skills/action-update-step@v1 to update steps.
- I fixed the YAML files so that the workflows could function without any error or skip.
- 3-fix-broken-sidebar.yml is now triggered by `pull_request` and checks if `github.event.pull_request.body` contains 'Closes'.
- I changed the style of conditional expressions in the YAML files.
- I clearly indicated the wait in README.md.
- I enabled echoing workflow commands.

### Check off the following:

- [x] For workflow changes, I have verified the Actions workflows function as expected.
- [x] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by sinsukehlab** [comment]
I have fixed workflows lest Actions should run in this repository.

**Comment by sinsukehlab** [comment]
Hmm.... :thinking:
I am unhappy about #13 because it is not a real solution to the problem. :disappointed:
I reopen this PR now. :open_hands:

**Comment by sinsukehlab** [comment]
I have made a commit to make workflows use skills/action-update-step@v1 to update steps.
I have checked if the Action workflows function, and have found an error.
I will fix this error.

**Comment by sinsukehlab** [comment]
I will change the trigger for 3-fix-broken-sidebar.yml.
on: issue_comment

**Comment by sinsukehlab** [comment]
I will also fix YAML style.
Cf. #14

**Comment by sinsukehlab** [comment]
Some checks such as "Check if commented issue is closed and marked as duplicate" in Step 1 are now just skipped if the conditions are not met.
I will leave them behind for now.
What do you think?

**Comment by sinsukehlab** [comment]
Multi-line conditional expressions did not work well.
I will use single-line ones.

**Comment by sinsukehlab** [comment]
I have finally fixed this course! :tada:
I have generated a repository and verified the Actions workflows function as expected.

**Comment by sinsukehlab** [comment]
@heiskr @a-a-ron Hello. I **strongly** propose to merge this PR so that it can improve your great course. I reverted some commits by @github-actions and then updated GitHub Actions workflows. Now the workflows function as expected completely.

### Why:

The latest commits by @github-actions have updated STEP, README.md, and _sidebar.md.
STEP should be set to 0 when generated, and then be updated to 1 by @github-actions closing Step 0 in README.md.
Also, a check in Step 3 is skipped even if the learner follows the instructions.

### What's being changed:


- I reverted recent commits by @github-actions to reset STEP to 0.
- I then updated update-step.sh to enable it to close Step 0 in README.md.
- I also edited YAML files so that they could use skills/action-update-step@v1 to update steps.
- I fixed YAML files so that the workflows could function without any error or skip.
- 3-fix-broken-sidebar.yml is now triggered by `pull_request` and checks if `github.event.pull_request.body` contains 'Closes'.

### Check off the following:

- [x] For workflow changes, I have verified the Actions workflows function as expected.
- [x] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

**Review by heiskr — APPROVED** [review]

**Pull request merged**
